config/routes.rb
MuralSf::Application.routes.draw do
  resources :characters

  resources :locations
  
  resources :pins

  devise_for :users
  get 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'

  root :to => 'pins#index'

  

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	attr_accessible :description, :destory, :show, :edit, :image, :image_remote_url


	validates :description, presence: true
	validates :user_id, presence: true
	has_attached_file :image, styles: { medium: "320x240>"}
	validates_attachment :image, presence: true,
	                      content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
	                      size: { less_than: 5.megabytes }
	belongs_to :user

	def pin_params
	 params.require(:pin).permit(:description, :image)
	end

	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
    @locations = Location.all
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])
    if @location.save
      redirect_to @location, :notice => "Successfully created location."
    else
      render :action => 'new'
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location])
      redirect_to @location, :notice  => "Successfully updated location."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_url, :notice => "Successfully destroyed location."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end
  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new

    respond_to do |format|
    format.html # show.html.erb
    format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @pins = @user.pins.page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "Aaron Brown", "#" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
		  <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
		  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		  </a>

		  <!-- Be sure to leave the brand out there if you want it shown -->
		  <%= link_to "Mural San Francisco", root_path, class: "brand" %>

		  <!-- Everything you want hidden at 940px or less, place within here -->
		  <div class="nav-collapse collapse">
				<ul class='nav'>
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
				</ul>
			<ul class='nav pull-right'>
			<% if user_signed_in? %>
				<li><%= link_to "Add +", new_pin_path %></li>
				<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
			<% else %>	
				<li><%= link_to "Login", new_user_session_path %></li>
			<% end %>
			</ul>
		  </div>
    
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuralSf</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <% yield :head %>
</head>
<body>
	
	<%= render 'layouts/header' %>
	
	<div class="container">
 			<% flash.each do |name, msg| %>
       	 <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
	    <%= yield %>
	    <%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for(@location, html: { class: "form-horizontal"}) do |f| %> 

  <%= f.input :address, label: "Insert Address" %>
  <%= f.input :latitude, label: "Insert Latitude" %>
  <%= f.input :longitude, label: "Insert Longitude" %>

<% end %>

app/views/locations/edit.html.erb
<% "Edit Location" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<% "Locations" %>

<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
    <tr>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
      <td><%= link_to "Show", location %></td>
      <td><%= link_to "Edit", edit_location_path(location) %></td>
      <td><%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Location", new_location_path %></p>

app/views/locations/new.html.erb
<% "New Location" %>

<%= render 'form' %>

<p><%= link_to "Back to List", locations_path %></p>

app/views/locations/show.html.erb
<% "Location" %>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
	<li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
	<% end %>
</ul>


<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>
	<div class='center hero-unit'>
		<h1>Mural SF</h1>
		<p>
			This is the homepage for my application called Murals SF.<br>It will work to catalog and store user submitted photos of murals<br>located around San Francisco, CA.
		</p>
		<p>
		<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
		</p>
	</div>
<% end %>

app/views/pages/about.html.erb
<div class='center hero-unit'>
<h1>About</h1>
<p>
With so many beautiful murals all over the City, there should be a place to collect them, this will do that. In addition, it will allow users to geotag their images. The layout will be similar to Pinterest. 
</p>
</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>

  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
  <%= f.input :image_remote_url, label: "or enter a URL" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

<%= render "locations/show" %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p class="description">
		<%= pin.description %>
	</p>
	<p>
		<strong>
			Posted by <%= link_to pin.user.name, pin.user %>
		</strong>
	</p>
	<% if current_user == pin.user %>
		<p>
			<%= link_to 'Edit', edit_pin_path(pin) %>
			<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' 
				} %>
		</p>
	<% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>
  

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
    $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
		<div class="span6 offset3">
			<div class="well">
			<%=  image_tag @pin.image %>
			<p>
			  <%= @pin.description %>
			</p>
			<p>
			  <%= @pin.user.name %>
			</p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
				<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>